### ISSUE TITLE
Fatal signal 11 , randomly appears if we get bitfield of pieces.

### ISSUE THREAD

**Issue by mianharisali** [frostwire/frostwire-jlibtorrent#127]
11-14 15:09:48.541 18793-19162/com.example.bilalkhalid.torrentdownloadsample A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x198 in tid 19162 (Thread-7)
                                                                                     
                                                                                     [ 11-14 15:09:48.541   377:  377 W/         ]
                                                                                     debuggerd: handling request: pid=18793 uid=10315 gid=10315 tid=19162
11-14 15:09:48.618 19163-19163/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-14 15:09:48.618 19163-19163/? A/DEBUG: Build fingerprint: 'google/angler/angler:7.0/NRD90M/3085278:user/release-keys'
11-14 15:09:48.618 19163-19163/? A/DEBUG: Revision: '0'
11-14 15:09:48.618 19163-19163/? A/DEBUG: ABI: 'arm64'
11-14 15:09:48.618 19163-19163/? A/DEBUG: pid: 18793, tid: 19162, name: Thread-7  >>> com.example.bilalkhalid.torrentdownloadsample <<<
11-14 15:09:48.618 19163-19163/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x198
11-14 15:09:48.618 19163-19163/? A/DEBUG:     x0   00000079a2a67b80  x1   00000079a25fea64  x2   00000079b7055ed8  x3   00000079a25fea68
11-14 15:09:48.619 19163-19163/? A/DEBUG:     x4   0000000000000cb6  x5   0000000000000000  x6   00000079a52b4038  x7   0000000000000000
11-14 15:09:48.619 19163-19163/? A/DEBUG:     x8   0000000000000194  x9   0000000000000000  x10  0000000000430000  x11  0000000000080011
11-14 15:09:48.619 19163-19163/? A/DEBUG:     x12  00000079a25fe9a8  x13  0000000000000000  x14  0000000000000000  x15  001f2d26b26ee111
11-14 15:09:48.619 19163-19163/? A/DEBUG:     x16  00000079a25fea68  x17  0000000000259700  x18  00000079be4b28b0  x19  00000079a2a64600
11-14 15:09:48.619 19163-19163/? A/DEBUG:     x20  00000079a324c144  x21  00000000130e3f10  x22  0000000000000cb6  x23  00000000130e3ee0
11-14 15:09:48.619 19163-19163/? A/DEBUG:     x24  00000000130e3eb0  x25  0000000000000cb6  x26  000000006f2177a8  x27  0000000000000ff9
11-14 15:09:48.619 19163-19163/? A/DEBUG:     x28  000000006f55daf8  x29  00000079a25feee8  x30  00000079a5354eec
11-14 15:09:48.619 19163-19163/? A/DEBUG:     sp   00000079a25fea50  pc   00000079a324c15c  pstate 0000000020000000
11-14 15:09:48.620 19163-19163/? A/DEBUG: backtrace:
11-14 15:09:48.620 19163-19163/? A/DEBUG:     #00 pc 000000000020d15c  /data/app/com.example.bilalkhalid.torrentdownloadsample-1/lib/arm64/libjlibtorrent.so (Java_com_frostwire_jlibtorrent_swig_libtorrent_1jni_bitfield_1get_1bit+24)
11-14 15:09:48.621 19163-19163/? A/DEBUG:     #01 pc 000000000008eee8  /data/data/com.example.bilalkhalid.torrentdownloadsample/cache/slice-jlibtorrent-1.2.0.2_220e90df8e4624470ea2dc947c803a5076816418-classes.dex (offset 0xbd000)
11-14 15:09:49.719 899-3279/? E/InputDispatcher: channel '3fa3b26 com.example.bilalkhalid.torrentdownloadsample/com.example.bilalkhalid.torrentdownloadsample.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
11-14 15:09:49.779 19189-19196/? E/art: Failed sending reply to debugger: Broken pipe
11-14 15:09:50.526 19189-19189/? E/RecyclerView: No adapter attached; skipping layout
11-14 15:09:59.961 899-19180/? E/NativeCrashListener: Unable to report native crash
                                                      java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Set.contains(java.lang.Object)' on a null object reference
                                                          at com.android.server.am.AppErrors.crashApplicationInner(AppErrors.java:389)
                                                          at com.android.server.am.AppErrors.crashApplication(AppErrors.java:309)
                                                          at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:13226)
                                                          at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
11-14 15:10:05.591 19189-19189/com.example.bilalkhalid.torrentdownloadsample E/numbp: 62

**Comment by mianharisali** [comment]
i just tested , it occurs when we have high number of pieces.
last crash was with 14000 pieces.

**Comment by aldenml** [comment]
What version of `jlibtorrent` is this?

**Comment by mianharisali** [comment]
1.2.0.2

it crashed on 5000 pieces too , real strange.

**Comment by aldenml** [comment]
strange indeed, let me review this

**Comment by mianharisali** [comment]
it appears randomly on 5000 pieces , but on 14000 pieces it just crashes.

**Comment by aldenml** [comment]
is your project open source? I would like to take a look at it

**Comment by mianharisali** [comment]
its not open source , but i just tested it same code works well on 1.1.1.40

**Comment by gubatron** [comment]
I know some changes were done to use bitfield CPU op extensions for 1.2 for some architectures, on what CPU architecture are you getting this crash? (can't see it on the crash report)

**Comment by aldenml** [comment]
```
11-14 15:09:48.618 19163-19163/? A/DEBUG: ABI: 'arm64'
```

**Comment by gubatron** [comment]
ha, so it's probably related to NEON?
gotta add that stress test unit test case.

@mianharisali what is the (min) piece size you have when you perform your 14k piece test?
[so I can build a torrent and test over here]

**Comment by mianharisali** [comment]
here are the details.
14035 X 16.4Kb

**Comment by gubatron** [comment]
Thank you!

**Comment by aldenml** [comment]
internally when you get the `pieces` bitfield, what are you getting is a reference to the field in the `torrent_status`. If the `torrent_status` is garbage collected, you will end up with an reference and crash. Can you post the relevant code to see the pattern you are using?

**Comment by mianharisali** [comment]
@gubatron sorry this was the correct information.
14035 X 4.2Mb

**Comment by mianharisali** [comment]
@aldenml 
`public boolean[] getPiecesDownloadInfo(String infoHash) {


        Bitfield bitF = session.find(new Sha1Hash(infoHash)).status().pieces();
        int size = bitF.swig().size();
        
        boolean[] bolList = new boolean[bitF.swig().size()];
        for (int i = 0; i < size; i++) {
            bolList[i]=(bitF.swig().get_bit(i));
        }
        return bolList;
    }`

**Comment by aldenml** [comment]
as I imagine, once you get the `bitF`, the TorrentStatus is free to be GCed. This should be fixed with https://github.com/frostwire/frostwire-jlibtorrent/commit/7cda563cf4fe141e2b5d7bbd983370c238ba0885 in the next version

**Comment by aldenml** [comment]
In the meantime, try to keep a reference to the torrent status and perform a dummy operation on it just before the `return` (to prevent that it's removed by optimizations)

**Comment by mianharisali** [comment]
@aldenml  thanks :) , i will try that.

**Comment by mianharisali** [comment]
@aldenml i tried that , it does not work all the time , it still crashes.

**Comment by mianharisali** [comment]
@aldenml any update when the next update will come?

**Comment by aldenml** [comment]
I was waiting for some commits in `libtorrent` (the merge from branch `RC_1_1`) but I think I can't delay it anymore.

**Comment by mianharisali** [comment]
@aldenml great , we are working on a app , and i think we have some more issues to report. but we are making sure that everything is fine on our end. i was thinking that may be next version will resolve a lot of things.

**Comment by aldenml** [comment]
`1.2.0.5` is out, give it a try and let me know if the problem persists

**Comment by mianharisali** [comment]
i have tested it , it is working fine. i will reopen if i encounter that problem again.
Thanks 👍

**Comment by aldenml** [comment]
@mianharisali How is that you are getting the bitfield without using `torrent_handle::query_pieces`?

**Comment by mianharisali** [comment]
@aldenml  yes i am using pieces flag in status object.
